version: "3"
services:
  next-instagram:
    container_name: next-instagram
    image: d1ndonlymdhe/next-instagram-docker:build
    environment:
      - MONGO_URI=mongodb://mongo:27017/instagram
    restart: always
    build: .
    networks:
      - my_network
    ports:
      - "3000:3000"
    links:
      - mongo
  chat-server:
    container_name: chat-server
    image: d1ndonlymdhe/chat-server:build
    environment:
      - MONGO_URI=mongodb://mongo:27017/instagram
    restart: always
    build: .
    networks:
      - my_network
    ports:
     - "4000:4000"
    links:
     - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - my_network
    ports:
      - '27018:27017'
networks:
  my_network:
    external: true
